### PR TITLE
moved dockerifles to folders

### PR DESCRIPTION
**Pull request by shimwell**
This is a small PR that moves and renames the dockerfiles. This has a few advantages

First as the files are named Dockerfile they gain syntax highlighting form editors such as VScode

Before
Screenshot from 2021-03-18 13-42-24

After
Screenshot from 2021-03-18 13-42-04

Another advantage is that the build command can be shortened 

Before
```docker build -f pymoab-py2-18.04 -t pymoab2 .```

After 
```docker build -t pymoab2 .```

Finally the last advantage is potential speed increase if you have other files in that folder . When building a Dockerfile the first stage  is that all local files / folders are loading into the memory just incase the Dockerfile has a COPY command then it has access to these files. You might notice things like this when building a Dockerfile that is in a low down folder. This is not really the case for this repo as it only loads up a few files, but zero is better than 3

Screenshot from 2021-03-18 13-46-01

### CODE REVIEW

**Review by kkiesling — COMMENTED** [review]
This looks good to me, but I just want to double check with @bam241 or @gonuke that the automatic build on dockerhub would still work (or can be updated to work properly) before merging.

**Comment by shimwell** [comment]
Oh I can help with that as well, would you like them to be built on the CI

**Comment by gonuke** [comment]
We use dockerhub's automatic capabilities for this, so would just have to change which file those autobuilds look at

**Comment by shimwell** [comment]
Adding a file like this can do the dockerbuild and publish on dockerhub if you like
https://github.com/ukaea/paramak/blob/main/.github/workflows/dockerhub-publish-stable.yml

It is a little easier to manage than the dockerhub based build (avoids shared account requirment)

**Comment by gonuke** [comment]
Thanks @Shimwell - I'll merge this and we can revisit the github action as a separate matter

**Pull request merged**
