### PR TITLE
Adding github actions to build and publish docker images on dockerhub

### PR DESCRIPTION
**Pull request by shimwell**
This PR adds GitHub actions to automate the building of the dockerfiles in this repository and publishing on dockerhub

for this to work two repository secrets will need to be added as the action makes use of ...
```
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
```

You can see from the github action runs on my fork that this has been successfully building the three images 

https://github.com/Shimwell/dockerfiles/actions

They were also uploaded to my dockerhub just to test https://hub.docker.com/u/shimwell

Naturally this GitHub action will upload to the Svalinn dockerhub but I just wanted to check everything works

### CODE REVIEW

**Comment by gonuke** [comment]
I've asked @bam241 to take a look at this, since I think he is most up-to-date on existing dockerhub credentials

**Comment by shimwell** [comment]
This is a probably quite low priority compared to the other good work being done on Svalinn repo.

I just made it as an example so we can consider the options for build docker images.

**Comment by gonuke** [comment]
> This is a probably quite low priority compared to the other good work being done on Svalinn repo.
> 
> I just made it as an example so we can consider the options for build docker images.

But also won't take much effort....

**Comment by shimwell** [comment]
Closing this one as it is not needed anymore thanks to #12

**Pull request closed without merging**
